import fs from 'node:fs'
import path from 'node:path'
import { scanRepo, looksLikeScratch } from './scan.mjs'
import { extractTokens, colorTokens } from './tokens.mjs'
import { extractComponents, nativeEquivalentsPresent } from './components.mjs'
import { detectArchetypes } from './archetypes.mjs'
import { deriveDefactoPalette } from './palette.mjs'

export const CONTRACT_DIR = '.uxproof'
const MANUAL_START = '<!-- uxproof:manual-start -->'
const MANUAL_END = '<!-- uxproof:manual-end -->'

/**
 * A contract is only as good as what it read. Flag the case that silently
 * ruins one: scratch or generated stylesheets outweighing the real ones.
 */
function contractWarnings(sources, totalTokens) {
  if (!totalTokens) return []
  const scratch = sources.filter((s) => looksLikeScratch(s.file))
  const scratchTokens = scratch.reduce((sum, s) => sum + s.tokenCount, 0)
  if (!scratchTokens) return []
  const share = Math.round((100 * scratchTokens) / totalTokens)
  if (share < 20) return []
  return [
    `${share}% of tokens (${scratchTokens} of ${totalTokens}) come from files that look like scratch or generated output: ` +
      `${scratch.slice(0, 3).map((s) => s.file).join(', ')}${scratch.length > 3 ? ', …' : ''}. ` +
      `Delete or exclude them and re-run \`uxproof sync\` — a contract judging by throwaway files is not your design system.`,
  ]
}

export function buildContract(root) {
  const scan = scanRepo(root)
  const { sources, tokens } = extractTokens(root, scan.styling.cssFiles)
  const components = extractComponents(root, scan.componentRoots)
  const archetypes = detectArchetypes(root)
  // No declared tokens: document the de facto palette instead. Proposed
  // tokens never arm the audit (colorTokens stays 0).
  const derivedPalette = colorTokens(tokens).length === 0 ? deriveDefactoPalette(root) : []
  const allTokens = derivedPalette.length ? [...tokens, ...derivedPalette] : tokens
  const warnings = contractWarnings(sources, tokens.length)
  return {
    version: 1,
    generatedBy: 'uxproof',
    framework: scan.framework,
    workspace: scan.workspace,
    styling: {
      system: scan.styling.system,
      tailwind: scan.styling.tailwind,
      tokenSources: sources.slice(0, 10),
    },
    libraries: scan.libraries,
    componentRoots: scan.componentRoots,
    nativeEquivalents: nativeEquivalentsPresent(components),
    archetypes,
    warnings,
    counts: {
      tokens: tokens.length,
      colorTokens: colorTokens(tokens).length,
      components: components.length,
      proposedColors: derivedPalette.length,
    },
    _tokens: allTokens,
    _components: components,
  }
}

function preservedManualSection(file) {
  if (!fs.existsSync(file)) return null
  const existing = fs.readFileSync(file, 'utf8')
  const start = existing.indexOf(MANUAL_START)
  const end = existing.indexOf(MANUAL_END)
  if (start === -1 || end === -1 || end < start) return null
  return existing.slice(start + MANUAL_START.length, end).trim()
}

function renderConventions(contract, manualSection) {
  const lines = []
  lines.push('# House rules')
  lines.push('')
  lines.push('Generated by `uxproof init` from what this repo actually does. Regenerate with `uxproof sync`; only the manual section below survives regeneration — put your team\'s judgment calls there.')
  lines.push('')
  lines.push('## Stack')
  lines.push('')
  lines.push(`- Framework: ${contract.framework}${contract.workspace ? ' (workspace/monorepo)' : ''}`)
  lines.push(`- Styling: ${contract.styling.system}${contract.styling.tailwind ? ` (tailwind v${contract.styling.tailwind.version})` : ''}`)
  for (const [role, packages] of Object.entries(contract.libraries)) {
    lines.push(`- ${role}: ${packages.join(', ')}`)
  }
  lines.push('')
  lines.push('## Design tokens')
  lines.push('')
  lines.push(`${contract.counts.tokens} custom properties found (${contract.counts.colorTokens} colors). Sources:`)
  lines.push('')
  for (const source of contract.styling.tokenSources) {
    lines.push(`- \`${source.file}\` (${source.tokenCount} tokens)`)
  }
  lines.push('')
  lines.push('Rule: colors come from tokens. A raw hex/rgb value in component code is a finding unless the manual section grants an exception.')
  lines.push('')
  for (const warning of contract.warnings ?? []) {
    lines.push(`> ⚠️ ${warning}`)
    lines.push('')
  }
  if (contract.counts.proposedColors > 0) {
    lines.push('### Proposed palette (derived from code)')
    lines.push('')
    lines.push(`No declared tokens were found, so the ${contract.counts.proposedColors} colors above marked \`proposed-*\` are the palette this codebase ALREADY uses, clustered perceptually from its literals. This is day one of a design system, not a rule yet: rename the ones you keep, declare them as CSS custom properties, re-run \`uxproof sync\` — the audit arms itself only once declared tokens exist.`)
    lines.push('')
  }
  lines.push('## Components')
  lines.push('')
  lines.push(`${contract.counts.components} components registered from:`)
  lines.push('')
  for (const rootDir of contract.componentRoots) {
    lines.push(`- \`${rootDir.dir}\` (${rootDir.fileCount} files)`)
  }
  lines.push('')
  if (contract.nativeEquivalents.length) {
    lines.push('Rule: prefer the house component over the raw element:')
    lines.push('')
    for (const { element, component } of contract.nativeEquivalents) {
      lines.push(`- \`<${element}>\` → \`<${component}>\``)
    }
    lines.push('')
  }
  if (contract.archetypes?.length) {
    lines.push('## Screen shapes')
    lines.push('')
    lines.push('Building a new screen? Find its shape below and model yours on the examples — structure, naming, states — instead of starting blank.')
    lines.push('')
    for (const { kind, count, examples } of contract.archetypes) {
      lines.push(`- **${kind}** (${count} screen${count === 1 ? '' : 's'}): ${examples.map((e) => `\`${e}\``).join(', ')}`)
    }
    lines.push('')
  }
  lines.push('## Manual rules')
  lines.push('')
  lines.push(MANUAL_START)
  lines.push(manualSection ?? '_Add the rules only your team can know: naming, tone, when to break the defaults. This section survives `uxproof sync`._')
  lines.push(MANUAL_END)
  lines.push('')
  return lines.join('\n')
}

export function writeContract(root, contract) {
  const dir = path.join(root, CONTRACT_DIR)
  fs.mkdirSync(dir, { recursive: true })

  const { _tokens, _components, ...publicContract } = contract
  fs.writeFileSync(path.join(dir, 'contract.json'), JSON.stringify(publicContract, null, 2) + '\n')
  fs.writeFileSync(path.join(dir, 'tokens.json'), JSON.stringify(_tokens, null, 2) + '\n')
  fs.writeFileSync(path.join(dir, 'components.json'), JSON.stringify(_components, null, 2) + '\n')

  const conventionsFile = path.join(dir, 'conventions.md')
  const manual = preservedManualSection(conventionsFile)
  fs.writeFileSync(conventionsFile, renderConventions(contract, manual))

  return dir
}

export function readContract(root) {
  const dir = path.join(root, CONTRACT_DIR)
  const read = (name) => JSON.parse(fs.readFileSync(path.join(dir, name), 'utf8'))
  return {
    contract: read('contract.json'),
    tokens: read('tokens.json'),
    components: read('components.json'),
  }
}

export function hasContract(root) {
  return fs.existsSync(path.join(root, CONTRACT_DIR, 'contract.json'))
}
